### ISSUE TITLE
Request: idle/low cpu priority and running as service

### ISSUE THREAD

**Issue by gijs007** [canton7/SyncTrayzor#143]
Would it be possible to set syncthing to idle/low priority instead of below normal?
I've noticed it using a lot of CPU and still causing lag in the OS with the below normal option.

Additionally it would be good to have the ability to run synctrayzor and synchting as a service, so it can run unattended and automatically be restarted if it crashes.

**Comment by canton7** [comment]
I could certainly add more Syncthing priority levels but I'm afraid the service stuff will never happen. It will destroy the multiuser support, and require a significant rewrite (since there is an awful lot of chatter between the UI, tray icon, and syncthing itself which will need to be reworked).

Syncthing is probably already being restarted if it crashes, no? (and if not, I should fix that) and a SyncTrayzor crash should reported, not ignored :wink: What other advantages do you see to a service?

**Comment by gijs007** [comment]
Fair enough. The only other advantage is that a user doesn't have to be logged in for it to start. This would be useful for servers.

**Comment by canton7** [comment]
Sure, but in that case a swanky UI and tray icon are pretty useless too: just run Syncthing as a service (there are plenty of preexisting tuts, and even installers, which let you do this). 

Multiple system users don't go well with services: we'd have to run one service per user in order to get the permissions right, and then people would complain that there were multiple syncthing instances taking all of their system resources...

**Comment by gijs007** [comment]
Depends, it's good to have an UI when you want to check on things but to have the process run in the background.

Perhaps it's an idea to have it as a option in the menu for people who don't have multiple users that want to use synching at the same time.

**Comment by canton7** [comment]
It's possible certainly: it's also probably a couple of months of all of my lunch breaks, weekends, and evenings, all for something which is only useful to a very small proportion of users. It's simply far too much complexity and time for something which is useful to so few.

**Comment by canton7** [comment]
Also remember that moat servers run headless: loading the Web UI directly is easier than logging in over rdp and opening a tray application.

**Comment by gijs007** [comment]
Another advantage is the auto updating and the automatic pushing of modified files. 

Perhaps synctrayzor itself could be made as a service and then to have a separate user interface application/web browser access or part of Synchtrayzors functionality could be added in to Syncthing.

But if it's indeed a lot of work then I suppose I could work around it by having the server automatically log in and then lock the desktop (although it's a minor security risk)

**Comment by canton7** [comment]
Righty, multiple priority levels are in. You'll be able to download a build from here https://ci.appveyor.com/project/canton7/synctrayzor/build/artifacts shortly
