### ISSUE TITLE
Suggestion:  Don't sync on metered networks

### ISSUE THREAD

**Issue by MikeBishop** [canton7/SyncTrayzor#167]
I raised [this suggestion](https://github.com/syncthing/syncthing/issues/2426#issuecomment-153331630) on the Syncthing repo, and was told that since this requires platform-specific calls it belongs in the platform-specific wrapper.

Basically, my request is that Syncthing not run when it's on a metered network (e.g. tethered to my cell phone) so it doesn't burn through my data allotment for the month when I'm not looking.  Win8+ exposes a way to determine whether the currently connected network has been marked as metered:  The [NLM_CONNECTION_COST](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448264(v=vs.85).aspx) enum returned by [INetworkCostManager::GetCost](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448261(v=vs.85).aspx).  If the result is Fixed or Variable, you probably shouldn't sync.  "Unknown" might be worth a separate config; I don't know how often that gets returned, but it would be unknown on older versions of Windows (i.e. Win7 or earlier) where the interface hadn't been added yet.

Interfaces become metered in a couple different ways:

  - Mobile broadband interfaces are assumed to be metered by default; users or operators can override the assumption.
  - Wi-Fi networks are assumed to be unrestricted by default; users can manually mark networks as metered
  - There's an IU a Wi-Fi access point can set to announce itself as metered, and Windows will pick that up at connection time (Windows Phones do this in Connection Sharing mode; don't know about other phones.)
  - Unfortunately, there's no way to mark an Ethernet interface as metered; this is an unpleasant gap, in my opinion.

**Comment by canton7** [comment]
I *think* this will be possible, given that I have to develop this on win7 and build on Windows Server 2012... Let me have a play at home later this week.

**Comment by canton7** [comment]
It might make most sense to combine this with device pausing (coming in v0.12).

**Comment by canton7** [comment]
Looks like it's going to be harder than I first though: the generate interop assemblies look like they might be a bit buggy (?), at any rate I've yet to find a way of calling the appropriate method correctly ><

**Comment by kc0tfb** [comment]
I don't want to add complexity if you're already frustrated but when it's figured out ... it would be desirable to pause anything going through the default gateway on a metered network while still allowing sync to things on the local subnet. (e.g. My son and I each tether to my phone's hotspot; our laptops are still syncing while everything else pauses).

**Comment by canton7** [comment]
Apparently `INetworkCostManager::GetCost` allows you to get the cost associated with the first hop of talking to a given IP. I haven't yet found the correct way of calling it though: it's new enough that there are very few code examples of calling it fro any language, never mind from C# via COM interop.

**Comment by kc0tfb** [comment]
First hop to get to a device on a local subnet should (according to IP routing, at least) be the local interface. First hop to anything else would be the default gateway.  I'm not sure if there's an easier way to determine this, although it shouldn't be too hard to write some test code (once the interface is figured out, that is) and iterate over a number of endpoints to see if this is true.

Another objective is keeping track of what was paused because of network metering and what the user manually paused (which should not un-pause when we get to an unmetered network).

**Comment by MikeBishop** [comment]
Note also that `If NULL, this method will instead return the cost associated with the preferred connection used for machine Internet connectivity.`  You can simply request the cost of the Internet connection.

The thornier question is whether peers on the local network should be paused or not -- if the first hop is Wi-Fi and the metering happens on the next hop, sync away.  If the first hop is a VPN connection which traverses mobile broadband and the peers are across the VPN, it should pause.  I'm not aware of a way to differentiate, and would probably pause out of an excess of caution.

**Comment by canton7** [comment]
The API doesn't cover more than the first hop anyway, so it's moot IMO.

**Comment by dsvf** [comment]
While we're compiling wishes - it would be nice if there were a way to override metering limitations for certain files/folders.

Example: I am on a metered connection. I have 10+GB of photos waiting to sync. I want to push one important document to someone I sync with.

I could now click the "force sync" button (if syncthing supports that). Or I could copy the file into the "always sync"-folder. Is something like this possible?

**Comment by canton7** [comment]
Syncthing doesn't currently provide a way of pausing folders, only devices. I think we need folder-pausing support before we can even begin to consider your suggestion, unfortunately.

**Comment by canton7** [comment]
I've finally figure out how to call `INetworkCostManager::GetCost`, so this is back in development.

Quick TODO list:

 - [] Introduce a Device Manager, which tracks the connectivity state of devices and allows them to be paused/unpaused
 - [] Create wrapper around `INetworkCostManager`, which goes from `IPAddress` -> cost. Also watches for cost changes. Handles not being able to load the interop library (Windows too old).
 - [] Create a Metered Network Manager - watches for connectivity events from the Device Manager and network cost change events from the `INetworkCostManager` wrapper. Has the logic to device when to pause/unpause devices - raises events when it does.
 - [] Integrate into the Alerts Manager - watches the Metered Network Manager for events, updates the alerts state
 - [] Bar Alerts need to watch the Alerts Manager for this new alert (thinking of displaying a blue bar at the top, saying "Devices X, Y, Z paused because networks A, B are metered")
 - [] The Tray Icon needs to watch the Alerts Manager for this new alert (thinking of displaying a blue 'paused' symbol if some devices are paused, or something)
 - [] Need to add to settings
 - [] Need the whole lot to degrade nicely if either Windows or Syncthing is too old.

**Comment by canton7** [comment]
Right, this should be working.

If anyone wants to test it out before the next release, you can grab a build from https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.2.255/artifacts

**Comment by dsvf** [comment]
Just to clarify, does this requite Windows 8 or newer?

**Comment by canton7** [comment]
Yes it does - Windows 7 doesn't have the concept of a metered network.

**Comment by canton7** [comment]
... the build works fine on Windows 7 and Vista: this feature just isn't available.
