### ISSUE TITLE
Easier debugging and log access, now that it's possible on the backend

### ISSUE THREAD

**Issue by calmh** [canton7/SyncTrayzor#175]
Since Syncthing 0.12, you can get a [list of debug facilities](http://docs.syncthing.net/rest/system-debug-get.html), present checkboxes for each of them, and push the results to [the same endpoint](http://docs.syncthing.net/rest/system-debug-post.html). The [log](http://docs.syncthing.net/rest/system-log-get.html) can also be polled every few seconds and be presented. Or we could just access the log on disk, probably (unless it's broken?). It would be neat if this was available as an easier option than setting STTRACE and restarting and stuff.

**Comment by canton7** [comment]
Sounds like a plan. I'll need to get slightly better infrastructure for working with multiple versions of Syncthing in first though: something I've been meaning to do for a while.

I already display Syncthing's stdout in a little window, so that should cover this? I think the log on disk is still broken in Windows. I should probably just tell syncthing to log to a specific file, then I can have a "show me the full log file"  button. 

Are those strings describing each of the trace options localised? I'm in a slightly awkward position of potentially displaying in a different language to the Syncthing gui (since the user can override the display language in Syncthing's gui, and I've got fewer translations than you anyway). If I display strings read directly from Syncthing in my interface, it would be nice if they were at least in the same language as my surrounding interface...

**Comment by calmh** [comment]
Yeah, stdout is fine. No, no localization on those...

**Comment by canton7** [comment]
Right. These don't persist over restarts. Users expect settings they set in SyncTrayzor to remain set for at least the life of SyncTrayzor, which means I'm going to have to store these myself and re-apply them when Syncthing (re)starts (probably using `STTRACE`, so that they're active in the long period before the GUI comes up).

However, this means that I need to notice when some other API client changes them, so that I can update my stored record of which ones to set on startup. Short of polling, is there any way of doing this?

**Comment by calmh** [comment]
I'd suggest ignoring what anyone else does and just do your thing from within Synctrayzor

**Comment by canton7** [comment]
To be honest, it will probably be easier to have Syncthing remember its logging settings across restarts. Would you have any objection to it doing this? If not, I'll try and get a PR together.

**Comment by calmh** [comment]
I don't necessarily have any objections to that, other than that it may be annoying to get right with the existing STTRACE envvar and so on.

**Comment by canton7** [comment]
It's fine, I implemented the "set STTRACE on startup and ignore anything which might want to change the debug facilities" approach.

**Comment by canton7** [comment]
Cool, this is in.

@calmh, @AudriusButkevicius: please ask SyncTrayzor users to use this new bit of UI instead of setting `STTRACE`:

They click the `Settings` button here:

![log-window](https://cloud.githubusercontent.com/assets/568104/12230695/ef8e2cb2-b849-11e5-8e81-e369ed19bf30.PNG)

Then check debug facilities here:

![log-settings](https://cloud.githubusercontent.com/assets/568104/12230704/fe42021a-b849-11e5-90be-ed4b1774c37a.png)
here:
