### ISSUE TITLE
Any reason why the client is trying to connect to some linode node everytime I open it from the tray?

### ISSUE THREAD

**Issue by gerroon** [canton7/SyncTrayzor#184]
Hi

I am wondering why the client is trying to connnect to some remote linode vps when I open the actual window from the tray? Is this some user behaviour tracking? I mean if this it needs to check for an update, that is fine but doing it everytime I enable the window sounds abit excessive.

Nice app btw. Keep up the good work.

**Comment by canton7** [comment]
Yeah this is the upgrade check. 

I think the original reasoning was that the user opening the application is a good point at which to get their attention to bug them about an upgrade. Checking for upgrades is very cheap, so there's no harm in doing it frequently.

It also ties in with the "Remind me later" option. If the user hit "Remind me later", they're probably busy with something else. Reminding them when they open the app is probably a good time.

However having said that, I'm not sure I've ever done an upgrade because I was prompted when I opened the app: normally it's because of the toast notifications. But then I never click "Remind me later", so... Maybe it would make sense to only check when the app is opened if the user previously clicked "Remind me later".

**Comment by canton7** [comment]
Righty, it'll only check on restore from tray if there's a 'remind me later' pending. Does this seem sensible?

**Comment by gerroon** [comment]
Yeah maybe you could let the user to schedule it in a way. Also it is working on port 80, it could better if it is https, depending on the content of the communcation.

**Comment by canton7** [comment]
Now that's Let's Encrypt is in public beta I've gotten around to putting a cert on that domain, so we could do that now. I'm slightly nervous of Let's Encrypt falling over in the next 6 months (new project and all that), but I guess I could always get a free cert from StartSSL....

I'm always nervous of making changes which could potentially break the upgrades system, as that impedes my ability to fix the mistake!

The information that's transmitted is documented [in the README](https://github.com/canton7/SyncTrayzor#will-synctrayzor-phone-home--give-away-my-secrets--etc).

**Comment by gerroon** [comment]
Well another option could be to ask user if the suer even wants upgrade mechanism during the initial start or install?

**Comment by canton7** [comment]
I really don't want to do that. I need my users to upgrade ASAP when a new version is released. Syncthing is free to change and break anything at any point, and I need to be able to push out a fix to users in a couple of days, or people are going to see things break.

The option to disable it is there in the settings if anyone does feel strongly about it.
