### ISSUE TITLE
Register access denied

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#2]
Getting the following when running SyncTrayzor as normal user, need to run as Administrator for it to work properly

The message says "Register access denied"

![image](https://cloud.githubusercontent.com/assets/613363/6328726/9c254420-bb6a-11e4-896f-54332f9872ec.png)

**Comment by canton7** [comment]
"Registry access is not allowed", says unlocalize.com. It's true, I'm assuming SyncTrayzor can access HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run in order to read/set/clear the key which allows it to start on login. This is usually the case, but apparently not always

I think the most sensible thing to do is probably gracefully degrade SyncTrayzor's functionality here if registry access isn't available - not providing an option in the settings to start/not start on login, etc. Then the user has to rely on the installer to change this setting, which prompts for administrator access.

**Comment by jkaberg** [comment]
Sounds good to me :) Good work!

**Comment by canton7** [comment]
Out of curiosity: if you open regedit.exe and browse to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run, then right-click the Run folder and select Permissions, what permissions does your user have? I'm expecting you to not have "Full Control", but do you have "Read"?

**Comment by jkaberg** [comment]
Yeah, Read

**Comment by canton7** [comment]
All your issues should be fixed in v1.0.2. SyncTrayzor should prompt you to download this. Let me know if you have any more issues.

**Comment by jkaberg** [comment]
Thanks a bunch! Will test and report back if any issues :-)
