### ISSUE TITLE
connect to an already running syncthing instance

### ISSUE THREAD

**Issue by ducch** [canton7/SyncTrayzor#247]
Syncthing is already running as a service, and I'd just like SyncTrayzor to "connect" to that running instance of Syncthing and administer it, instead of running another one.
Is that possible? If not, can I make a feature request for that?

**Comment by canton7** [comment]
It's not currently possible, and it's a fair amount of effort for little gain.

A few issues, off the top of my head:

- It currently assumes it can control what port Syncthing listens on, and what API key it uses
- It assumes it can capture the STDOUT of the Syncthing process
- It relies on being able to set things like the STTRACE environmental variable when Syncthing starts.
- The controls to start/stop Syncthing, etc, have to disappear when we're running in this mode.

**Comment by canton7** [comment]
This isn't going to happen, realistically.

**Comment by sroblin** [comment]
this remark is interesting because when you setup syncthing as service on a server and you want to administer it by a team of operators who connect on the machine by their own identity, it's not possible to use synctrayzor and the tool is unuseful. a mode to catch the current syncthing instance and control it (keeping the start/stop menu)   can be very interesting. the other consideration are  only technical and can be solved.

**Comment by canton7** [comment]
Correct, this tool is not suitable for running Syncthing as a service. Use nssm or similar, as use the Web UI.

**Comment by renawi94** [comment]
> it's a fair amount of effort for little gain

Well, the gain would be all the features of SyncTrayzor, primarily the notification on errors etc.
