### ISSUE TITLE
Clarify "Metered Network" notification

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#249]
This one is somewhat a followup to https://github.com/canton7/SyncTrayzor/issues/242.

Assume device A is running SyncTrayzor:
Once A connects to the metered network by itself, SyncTrayzor reports: 
![image](https://cloud.githubusercontent.com/assets/11633330/14232259/98a20e92-f9ac-11e5-904e-13ba445d69d8.png)
 following the list of every device on-line.

Such phrasing is incorrect, as it implies that the devices that are listed are each connected to metered network, while in fact only the current device A is.

Better phrasing would be something like: 
"Synchronization is suspended, because this device is connected to a metered network."

Unless you're handling it in a more advanced way - distinguishing between remote and local devices, and while on metered network pausing only the remote ones. In such case the following message may be good:
"The following devices have been paused, because they can be accessed only over metered network: <remote_devices_list>"

**Comment by canton7** [comment]
It's neither. 

When Syncthing connects to a device, we check to see whether it connected over a metered network (your computer can be connected to many networks at once, only some of which may be metered). If that network is metered, we pause the device.

If SyncTrayzor says "The following devices have been paused because they connected to a metered network: A, B, C", that means that Syncthing connected to devices A, B, C, and each connection was over a metered network, so we paused them all.

We can't know ahead of time whether a device *can* only be accessed over a metered network: we only know whether a connection to a device *has* been established over a metered network.

**Comment by scienmind** [comment]
I see, thanks for the clarification. Seems like a very reasonable way to do it.

I think, then, that just the following modification may be sufficient:

Current:
"The following devices have been paused, because they connected **to** a metered network: ..."
Proposal:
"The following devices have been paused, because they (**are**?) connected **via**/**over** a metered network: ..."

**Comment by canton7** [comment]
The "are" is incorrect: they're not currently connected, because we paused them.

"via"/"over" is an option.

**Comment by canton7** [comment]
Fixed in v1.1.9
