### ISSUE TITLE
ACTIVE MALWARE DETECTED

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#282]
Kaspersky Total Security 16.0.1.445c detected a Trojan Horse inside \AppData\Roaming\Synctrayzor\syncthing.exe.

Trojan Program: Trojan.Win32.Ebowla.ab

**Comment by ProactiveServices** [comment]
False positive
https://forum.syncthing.net/t/kaspersky-treats-syncthing-as-virus/7659

**Comment by canton7** [comment]
This was a kaspersky issue which has now (apparently) been fixed by them

**Comment by jebeld17** [comment]
Who is to say Kaspersky was the troublemaker? I find it more likely the git got an infected binary.

**Comment by canton7** [comment]
If you read the forum thread which @ProactiveServices kindly linked you to, you'll see that:

1. Syncthing 0.13.7 was verified beyond reasonable doubt to to be free from malware. A build from source was done in a pristine environment, and was as close to byte-for-byte identical to the official release as can be expected.
2. The issue was reported to Kaspersky. They released updates to their definitions, and no longer identify Syncthing as malware.

Therefore I am certain that the official Syncthing release is free from malware, and the Kaspersky alert was (note: it no longer is) a false positive.

I have no idea what "git got an infected binary" means. Git deals with source, not binaries. 

Finally, this is the wrong repository: this is the repo for SyncTrayzor, not Syncthing. The correct issue for this is https://github.com/syncthing/syncthing/issues/3329, which you also opened and was closed with the same explanation as I've given here.
