### ISSUE TITLE
Force/Recall update prompt

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#302]
I recently wanted to update but had clicked away the update prompt. Many other pieces of software offer a "check for update" option under Help -> About. I could admittedly just restart SyncTrayzor all the time or wait or download the installer, but it would be nice to be able to manually trigger the update.

**Comment by canton7** [comment]
Agreed. The help -> about window does check for updates, but won't allow them to be automatically installed. 

The plan (there's another issue open for this) is to have the about page show the progress of the auto-updater (checking/downloading/verifying/any errors/etc), and if it's downloaded an update then it would say whether it's been ignored, etc, and allow you to view the changelog and kick off the installation process. 

That's the plan, anyway. Just need some time to implement it...

**Comment by canton7** [comment]
Dup pf #236

**Comment by Hard-Wired** [comment]
Would this also reinstall SyncTrazor in place without having to reinstall Syncthing from scratch?

**Comment by Hard-Wired** [comment]
Sorry, I realize I did not word my question very well.

Say I have a broken SyncTrayzor installation due to some other system problem not related to SyncTrayzor or Syncthing, which corrupts their installation (registry/configs/etc). I'd like to automatically have SyncTrayzor repair itself in place without wiping all of the Syncthing linkages. Traditionally this type of function is provided by other software as a "Repair" option in the Windows Programs/Apps list as an alternative to Uninstalling.

Could or would this Force update feature do the same thing?

Currently, what is the best practice for fixing such a broken installation?

**Comment by canton7** [comment]
Just run the installer again.

That has nothing to do with this issue, which is about recalling the upgrade prompt if the user dismisses it. If there is no update available, there would be no upgrade prompt to show.

**Comment by canton7** [comment]
Closing as a dup of #217
