### ISSUE TITLE
Sync folder - portable mode

### ISSUE THREAD

**Issue by HyperCriSiS** [canton7/SyncTrayzor#310]
Hi,

I use syncthing to sync my USB stick. So far this works very well.
But for a better handling it would be nice to put this syncfolder in a "portable mode".
I thought of:
- Add this drive to the context menu of synctrayzor so you can eject it
  --> sync is paused and drive is ejected.
  --> put into watch mode as soon drive is ejected
  --> automatically sync when the drive is available again

Thanks and reagards,
Hyper

**Comment by canton7** [comment]
I don't think ejecting USB devices is within the scope of SyncTrayzor - I don't even know whether it's possible.

What's "watch mode"?

We already have a good amount of support for portable devices. We tear down the filesystem watchers gracefully when the drive disappears, and automatically notice when it reappears and set up the watchers again. What else do you want?

**Comment by scienmind** [comment]
I've used portable drives with syncthing in the past. The handling on syncthing's side was fine, it would detect the removals and halt folder's sync properly, just as mentioned above.

I had some major issues however, due to "unreliable device connections": occasionally the USB hub would decide to "semi-loose" the portable drive, without telling the OS about it. Which would make syncthing (and the whole OS actually) to think that device is still connected, but most of files are "unavailable/gone", which in turn would convince syncthing that those files are happily deleted, and it'd propagate the deletions further...

So I'd suggest to watch out for connectivity issued with the portable drive (if you are about to leave it syncing for prolonged periods) if none, good for you :)

Besides, once "folder pausing" (Syncthing's PR 3520) is implemented, you'll be able to manually stop folders from syncing/scanning and control it easily as well.

**Comment by HyperCriSiS** [comment]
Ok, maybe then it would be just enough to be able to pause this folder within the context menu.
Just for a better handling.

**Comment by canton7** [comment]
So... A separate 'Pause Folder...' option, underneath 'Open Folder'?

It seems odd to call out 'Pause Folder' especially here. There are many, many other things you can do with Syncthing. Why is 'Pause Folder' special? Why not pause device? Start a scan? Edit a folder? Add a new folder? etc.

**Comment by canton7** [comment]
Given that Syncthing doesn't even let you pause a folder, I'm going to close this as nothing to do.

**Comment by scienmind** [comment]
> It seems odd to call out 'Pause Folder' especially here. There are many, many other things you can do with Syncthing. Why is 'Pause Folder' special? Why not pause device? 

Because, as I understood, he asked about "portable mode" in context of using repository located on portable device. That's why I brought up "pausing repository".

And I agree, until ST supports "pausing", there isn't much to do here...
(hopefully https://github.com/syncthing/syncthing/pull/3520 will be finished not too far in the future ;) )
