### ISSUE TITLE
Feature: informative icon

### ISSUE THREAD

**Issue by jaxankey** [canton7/SyncTrayzor#317]
A thought: it'd be nice if the tray icon somehow differentiated between
- all known computers are online and sync'd (green icon, or normal icon with a green check in the corner?)
- all known computers (when last seen) were sync'd (the normal icon?)
- computers are known to be out of sync (pink icon, or normal icon with red X in corner?)

Cheers!

**Comment by canton7** [comment]
I'm worried about adding ever more colours and icons, as it becomes increasingly unlikely that anyone will guess what it means!

I agree it might make sense to warn the user of out of sync folders, etc, but if we do this, let's copy Syncthing's icon scheme - both the actual icons used, and the conditions for showing them. That's going to conflict with the extra stuff that SyncTrayzor needs to show (conflicts detected, and device disabled because of a metered network connection), so that needs some thought...

**Comment by canton7** [comment]
Closing, to avoid mass user confusion
