### ISSUE TITLE
configure confusion

### ISSUE THREAD

**Issue by dtxl** [canton7/SyncTrayzor#362]
On a W7 device on which a user was logged on, I installed yesterday SyncTrayzor as admin (using Shift + right click on the installer, choosing "Run as different user" with admin logon details). Then, as this user, I configured synthing to connect with other PCs. Today, after a reboot, all these settings had disappeared under the user's logon. But, when logged on as admin, the SyncTrayzor showed the setup of yesterday. I would expect settings made as a user to be and remain in that user's profile. What do I miss? Thanks.

**Comment by canton7** [comment]
You started the installer as the admin (rather than letting it prompt you for admin rights). When it offered to launch SyncTrayzor at the end of the installation process, SyncTrayzor was also launched as admin (since the installer only knows about the admin user, since it was launched as admin. It has no way of knowing about your user).

When a process runs as admin, it sees the admin's user profile. When it runs as your user, it sees your user's profile.

Therefore, yesterday, your settings were stored in the admin's user profile, under `C:\Users\Administrator\AppData\Local\Syncthing` for Syncthing's config, and `C:\Users\Administrator\AppData\Roaming\SyncTrayzor` for SyncTrayzor's config.

When you ran it today, under the user's login, it accessed the settings stored in `C:\Users\<You>\AppData\Local\Syncthing` and ``C:\Users\<You>\AppData\Roaming\SyncTrayzor`.

**Comment by dtxl** [comment]
I see, thanks for the explanation.
Therefore, SyncTrayzor shouldn't run automatically after the installation. Would the situation change by letting it prompt for admin rights?

**Comment by canton7** [comment]
It works fine if the installer prompts for admin rights - I've tested that.

**Comment by dtxl** [comment]
Ok, thank you.

**Comment by canton7** [comment]
(It's the same as any other installer which offers to start the application after installation).
