### ISSUE TITLE
Blocked by Windows Defender SmartScreen on Windows 10

### ISSUE THREAD

**Issue by vrischmann** [canton7/SyncTrayzor#365]
Hi,

not sure why but it looks like Windows Defender SmartScreen (first time I heard of SmartScreen, don't know what it is) blocks:
* downloading any of the Portable and Installer binary / zip of 1.1.16 when using Microsoft Edge
* executing the portable SyncTrayzor.exe
* executing the installer SyncTrayzorSetup

It happens with both architectures, x86 and x64.

I can confirm that 1.1.15 works without problem.

**Comment by canton7** [comment]
Thanks for the heads-up! Where did you download them from, and what browser did you use?

**Comment by vrischmann** [comment]
Microsoft Edge blocks the download. I downloaded the binaries with Google Chrome but then when I try to execute them it gets blocked by Windows.

**Comment by canton7** [comment]
OK, I've replicated it. Trying to figure out how to report false positives to Microsoft...

Meanwhile, if you set SmartScreen to "Warn" (under "App & browser control" in "Settings" -- typing "SmartScreen" into the start menu gets you there), then you can click "More info" in the "Windows protected your PC" window, then "Run anyway".

Very little changed between 1.1.15 and 1.1.16, so I'm not sure why it would start kicking off all of a sudden...

**Comment by canton7** [comment]
(Or if you view the file properties, you can check the "Unblock" checkbox).

**Comment by vrischmann** [comment]
Seems like it's fixed now, I just installed 1.1.16.

**Comment by canton7** [comment]
Awesome, thanks for the update.

Apparently Microsoft use a system of reputation: if your application is opened by a certain number of users which all report no issues, then Microsoft gives it a green light.

You can give yourself some starting reputation by signing the application with an EV certificate. However I'm not a company and anyway don't have the funds to get one, so that's not a viable path.

**Comment by vrischmann** [comment]
Good to know ! It's a shame there's no equivalent of Let's Encrypt for code signing certificates because from what I've seen it's prohibitively expensive.

**Comment by canton7** [comment]
The point of Let's Encrypt is to encrypt communication. You could be talking to someone who claims to be PayPal but who is actually malicious, and Let's Encrypt isn't involved. They only ensure that your communications to PayPal (or the fraudster) aren't intercepted.

EV certificates give you a lot of confidence that the person you're talking to is who they claim to be. With EV certificates, you can be confident that you're actually talking to PayPal, not a fraudster. That requires someone to make sure that the person requesting the EV certificate is actually PayPal (this includes face-to-face interviews over Skype, lots of document submission, etc, depending on who's doing it). All of that costs money, which is one of the reasons that EV certificates cost money.

EV certificates used for signing apps are the same: they make sure that the app is actually published by PayPal (or whoever), and not someone claiming to be PayPal. For this reason a system like Let's Encrypt will never work: you *need* that level of manual scrutiny and verification, because that's the entire point of EV certificates.
