### ISSUE TITLE
silent update

### ISSUE THREAD

**Issue by dtxl** [canton7/SyncTrayzor#366]
As in syncthing, it would be helpful to have an silent update option, i.e. SyncTrayzor doesn't show the Update window, but just install the latest update. Thanks.

**Comment by canton7** [comment]
That is not possible.

Publishers are supposed to install their applications into Program Files. You require administrator permissions to install stuff into Program Files, and this is a very good thing from a security perspective. (Some applications instead install into AppData, which doesn't require administrator permissions, but I refuse to do this on principle).

Since administrator permissions are required, I need to prompt for them. Therefore I need user interaction. I need the user to take positive action before prompting (noone's going to enter admin credentials into a prompt that appears out of the blue). Therefore I need the "Install Now" button.

**Comment by scienmind** [comment]
Adding an auto-update (with opt-out option) is a welcomed addition to help everyone's grandma stay up to date ...
Can you elaborate about the aversion to using AppData? AFAIK you keep the actual ST binary there...

On a related topic - update for "portable" installations in its current form creates a temporary copy of itself outside of installation folder, which requires more rights then writing stuff inside the folder:
Example: if the portable installation resides in the root of a hard drive, it'll always fail.

**Comment by dtxl** [comment]
I see. In an enterprise environment such a window often produces confusion about what's going on. Maybe, disabling the update and remote deployment is an option. Is it possible to deploy an update silently?

**Comment by canton7** [comment]
(Also bear in mind that I can't *switch* the upgrade strategy now without breaking everyone.)

> Can you elaborate about the aversion to using AppData? AFAIK you keep the actual ST binary there...

Once upon a time, I got a virus (which was entirely my fault). This thing ran around my hard drive injecting itself into every binary it could. All of my installations in AppData (and the ones directly in `C:\`) were rewritten to prompt for administrator privileges when they were run: this thing tried to use the trust established by existing applications to get itself administrator privileges. The applications in Program Files were not affected, and did not start presenting a security risk. That really drove home why you're supposed to put your applications somewhere protected, and your configuration can go somewhere less secure.

> On a related topic - update for "portable" installations in its current form creates a temporary copy of itself outside of installation folder, which requires more rights then writing stuff inside the folder:
Example: if the portable installation resides in the root of a hard drive, it'll always fail.

That wasn't something I was aware of. That probably deserves a separate issue, rather than being lumped in here.

> I see. In an enterprise environment such a window often produces confusion about what's going on. Maybe, disabling the update and remote deployment is an option. Is it possible to deploy an update silently?

Yep, the assumption is that you have a deployment management system in an enterprise environment.

The installer will give you its command-line flags if you pass `/?`, alternatively they're [documented here](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline). The file `SyncTrayzor.exe.config` contains a bunch of options which people in charge of deployment might find useful, including the default configuration file (where you can disable update checks, etc).

**Comment by dtxl** [comment]
Thanks!

**Comment by canton7** [comment]
... if there are other things you'd like to be able to control in order to do deployments, I'd be happy to hear them.

**Comment by scienmind** [comment]
> That really drove home why you're supposed to put your applications somewhere protected, and your configuration can go somewhere less secure.

That's an interesting point. And I tend to agree.

However, there are always trade-offs, as in: adding an extra "click" and requiring user's attention, means that a non-significant portion of the user base will never be up to date (maybe for SyncTrayzor it is insignificant, as it's not that widespread atm).

PlayStore for example - it defaults to auto-updates without prompts. Some people annoyed by the "voodoo-magic" changing stuff on their devices constantly. But overall it significantly improves everyone's security.
But windows is not android, and there is no sandboxing by design, so issues like your virus infection arise. Having a way to self update without user intervention/admin rights, while requiring automated authentication (i.e. verifiable signed update) would be the way to go. But we don't have that yet...

> ...portable updates...  -That probably deserves a separate issue

Opened: #368

**Comment by canton7** [comment]
> However, there are always trade-offs, as in: adding an extra "click" and requiring user's attention, means that a non-significant portion of the user base will never be up to date (maybe for SyncTrayzor it is insignificant, as it's not that widespread atm).

I released 1.1.16 on Saturday. Looking at the week leading up to that date, this is the distribution of versions which were checking for an update:

- 1.1.15: 83%
- 1.1.14: 9%
- 1.1.13: 4%
- 1.1.12: 1%
- 1.1.11: 0.7%
- 1.1.10: 0.5%

That's better than Syncthing manages (ignoring the fact that I push updates less frequently than Syncthing does. If you control for that, I'm still going pretty well).

**Comment by scienmind** [comment]
Yeah, the stats are not that bad at all, and controlling for incompatibility between ST 0.XX.0 versions, i'd say its pretty similar to ST.

The thing is, the more widespread it goes, the more non-techies you have, and people tend to click away/cancel all kinds of pop ups without giving it much thought. I had occurrences of friends complaining me about issues with <some_sw> (and couple of times with synctrayzor), usually to find out that they were not up to date and the issue has been fixed already.

My point is, that unattended updates increase security/stability. The tough question is how to do it safely without increasing attack surface at the save time...

**Comment by canton7** [comment]
Also bear in mind that the current update system took me about 30 hours to write. I don't have the sort of free time to come up with a hyper-complex system which maintains the same level of security.

**Comment by jebeld17** [comment]
Why not take advantage of the Windows Task Scheduler to handle updates on a timed, regular basis? This is how Google keeps Chrome up-to-date without constant interruptions and admin prompts.
[GoogleUpdates.zip](https://github.com/canton7/SyncTrayzor/files/1021982/GoogleUpdates.zip)

**Comment by canton7** [comment]
It doesn't translate to portable updates. Also running my own code with administrator privileges, which is going to do things like talk to the network, verify signatures, etc, makes me nervous, as there are various places for malware to slip in and give itself admin privileges.

**Comment by dtxl** [comment]
To me, creating a schedule as suggested by jebeld17 seems a way for silently updating SyncTrayzor (same as e.g. Chrome, Opera, FlashPlayer, Acrobat etc.). Now the question is, whether an update is automatically downloaded to %TEMP%\SyncTrayzor on its availability?

**Comment by canton7** [comment]
Guys, stop designing this. Unless you're prepared to write the code for it (and make it work for portable updates), this is not going to happen.

**Comment by dtxl** [comment]
Pardon me, but you offered me "... if there are other things you'd like to be able to control in order to do deployments, I'd be happy to hear them."
That question for support is beneath any coding. An answer helps me for my environment. I need simply to know, whether an update is automatically downloaded to %TEMP%\SyncTrayzor on its availability or not (even if the notification is disabled). Thank you in advance.

**Comment by canton7** [comment]
> Pardon me, but you offered me "... if there are other things you'd like to be able to control in order to do deployments, I'd be happy to hear them.

Let's look at the context:

> The file SyncTrayzor.exe.config contains a bunch of options which people in charge of deployment might find useful, including the default configuration file (where you can disable update checks, etc).

Maybe I should clarify: if there are other *install-time or runtime options* which you'd like to be able to control in order to do deployments, I'd be happy to hear them.

If SyncTrayzor is configured to check for updates, then updates are automatically downloaded. If it is not configured to check for updates, then updates are not automatically downloaded.

**Comment by dtxl** [comment]
Thanks for clarification. I understand your concerns and I'm sharing it. On the other side, I need a solution and therefore I test ideas. Your last post about downloading of updates was a missing piece of information. Thanks.
(Just to note, if you find this annoying (or boring), please, fell free to tell me and I'll stop asking on this topic without any hesitation or worries.)

**Comment by jebeld17** [comment]
Why not just not have the auto-update option available in the portable edition? A notice can also be posted in the update popups that the Portable version does not support automatic updates "at this time."


As for the potential of letting malware in, if I am thinking correctly, wouldn't Synctrayzor just use admin rights only during those scheduled events anyways? I mean, the app is going to need those administrator rights anyways whether the user presses the button or not. Having auto-update without offer and consideration to opt-out would certainly put you at-fault for system failures, _but if you give users that offer to allow auto-updates using benefit of the doubt their systems should be safe along with a consideration period and accept/decline buttons, that transfers the liability back over to the end-user,_ which negates your worries about system malware right there.

**Comment by canton7** [comment]
> @canton7 Why not just not have the auto-update option available in the portable edition? A notice can also be posted in the update popups that the Portable version does not support automatic updates "at this time."

See #82. I spent a good chunk of a couple of weekends adding automatic updates for portable users, in response to the pressure from them. Shall I let you deal with 2.5k angry portable users who just had automatic updates removed?

> I mean, the app is going to need those administrator rights anyways whether the user presses the button or not.

Currently I let Inno Setup (the installer framework) prompt for admin rights. I trust Inno Setup to be safe. I do not trust my ability to come up with a scheme where I end up launching the installer with admin rights, without some malware jumping in and getting me to launch it with admin rights instead.

There's another bit of complexity here, which is that I need to launch the updated SyncTrayzor as the user. If I kick of from a scheduled task, I've got to figure out which user (from potentially multiple logged-in users) to start it for.

> Having auto-update without offer and consideration to opt-out would certainly put you at-fault for system failures, but if you give users that offer to allow auto-updates using benefit of the doubt their systems should be safe along with a consideration period and accept/decline buttons, that transfers the liability back over to the end-user, which negates your worries about system malware right there.

No. If I write a shitty auto-update system which lets malware gain admin privileges, it is **my** fault regardless of whether the user opts to use it or not.

I don't know why I continue to argue with you. You're obviously not going to write this new system for me, and you obviously don't understand things like the consequences of removing a feature that thousands of people rely on, and opening risking putting rootkits on tens of thousands of people's machines.

What I do now is in line with what many open source projects do, has had a lot of time spent on it, has been thoroughly debugged, and *works*. To repeat what I said earlier, I am **not** going to put all other work on hold to completely rewrite it so that it instead does what a random person person on the internet thinks it should do.

Imagine I offered to give you a lift across the country. Would you point out everything about my driving that you didn't like, complain that my car wasn't the latest model, complain about my music, but never offer to do any of the driving yourself and never say thanks for the ride? No, that would be rude. But doing the same with an open source project is OK, and I don't get it.

This discussion is over. If you are actually prepared to put the work in yourself, then open a new issue and we'll discuss the specifics. However any future work:

1. Must work for portable users
2. Must not run the risk of running malware with admin rights
3. Must be as robust as the current system

**Comment by scienmind** [comment]
i'm no canton7, but:

>Why not just not have the auto-update option available in the portable edition?

It's already there, only the copy mechanism need to be adjusted (#368), no need to burn bridges...

> ...transfers the liability back over to the end-user, which negates your worries about system malware right there.

While it may "transfer the liability" to the user formally, the actual concern of sw safety remains. I don't think canton7's motivation is to "shift the blame", but rather to design SW in a way that does not increase attack surface. And I strongly support this position.
