### ISSUE TITLE
Does the per folder 'scan interval' setting mean anything at all?

### ISSUE THREAD

**Issue by prasanuv** [canton7/SyncTrayzor#390]
Default was 60 secs, but I increased this to 5 mins fearing excessive cpu usage. Was wondering if this is even being used anywhere, because shouldn't the file watcher already take care of this rendering any periodic scans redundant?

**Comment by canton7** [comment]
The filesystem watcher doesn't modify the scan interval. You can set the scan internal to something high, since the filesystem watcher should pick up on any changes without Syncthing having to rescan, but still scan now and then, in case the filesystem misses something (filesystem notifications aren't guaranteed).

**Comment by prasanuv** [comment]
Thanks! Relared question but probably not the right forum to ask - how is this handled in android? I don't see an equivalent setting for 'scan interval'..

**Comment by scienmind** [comment]
@prasanuv The setting is there on android, just visible from the web-ui only.

The native interface of android app displays only a subset of all settings and options. 
To get the "real thing" you need to access it via WebUI

And the right place for ST discussions is here: 
https://forum.syncthing.net/

**Comment by prasanuv** [comment]
Makes sense. Please feel free to close this.
