### ISSUE TITLE
Finished Syncing notification

### ISSUE THREAD

**Issue by jake404** [canton7/SyncTrayzor#393]
There is no global setting to disable the 'Finished Syncing' notification for all folders.

**Comment by canton7** [comment]
You are correct. What is the issue?

**Comment by jake404** [comment]
The above mentioned notifications are very annoying and having to change notifications for each folder on every computer is a pain. There are global settings for the other notifications so why not have one for this notification.

**Comment by canton7** [comment]
Like I said, there is one checkbox which disables the notification for all folders.

There isn't a "global" setting because the interaction of a global setting with per-folder settings is confusing for users. They enable the setting for a folder, yet there are no notifications: why? Then enable global notifications but some folders don't notify: why?

> having to change notifications for each folder on every computer is a pain

As I said in my previous message, you can click a single checkbox to disable all folders at once. This one right here:

![image](https://user-images.githubusercontent.com/568104/29067617-46de6a1c-7c2b-11e7-80ba-ededc4d74fc0.png)

**Comment by jake404** [comment]
Does that checkbox disable new folders as well? If so then the choice of UI components are unintuitive. Normally a checkbox above a list of checkboxes is a mass select/deselect only.

**Comment by canton7** [comment]
It is a mass deselect. Are you concerned about new folders, too?

Either way, a global setting is not really viable, for the reasons I explained above. I can put some logic in which says "If we're adding a new folder, and the notifications for all previous folders are disabled, then initially disable notifications for this folder as well". At least it's clear to someone who views the settings what's happening.

**Comment by jake404** [comment]
I feel that it would be more confusing that way. I would just use that top checkbox to disable all the checkboxes below it and also disable notifications completely. If that's not at all acceptable then your solution would be a decent compromise.

**Comment by canton7** [comment]
Cool. I'm pretty busy now, but there will hopefully be another release within the next couple of months.
