### ISSUE TITLE
SyncTrayzor start a conhost.exe but dont close it

### ISSUE THREAD

**Issue by beerisgood** [canton7/SyncTrayzor#394]
On Windows7 x64 SP1 with SyncTrayzor 1.1.16 Portable x64 (Syncthing 0.14.36) a conhost.exe start.
I use the "start minimized" option and i think because of that the conhost.exe start for start SyncTrayzor in commandline.
But the conhost.exe doesnt close. If i close it, nothing stop work so the conhost.exe isnt needed after start SyncTrayzor.

It would be nice if you just add a "exit" in the commandline so the conhost.exe prozess died.

**Comment by canton7** [comment]
Syncthing starts it, look:

![image](https://user-images.githubusercontent.com/568104/29187429-9eead6ea-7e07-11e7-86fe-45a5c1b5c203.png)

Syncthing is a console application

"Start minimized" also has nothing to do with it - letting SyncTrayzor start unminimized will have shown you that.

You can try taking this up on the Syncthing Forum, but I suspect you'll get the response "this is started because Syncthing is a console application".

**Comment by beerisgood** [comment]
Ah. Make sense
Thanks
