### ISSUE TITLE
Particular font issue on Windows

### ISSUE THREAD

**Issue by Merinorus** [canton7/SyncTrayzor#408]
Hi,
I installed a new font on Windows and SyncTrayzor started using it:
![synctayzor-font-issue](https://user-images.githubusercontent.com/3023499/30720629-96bf5058-9f28-11e7-93c7-396f500bc1c5.png)

This happened with the OpenType font named "Helvetica Ultra Compressed". Synctrayzor 1.1.18, Syncthing v0.14.18. The text is barely readable, to fix this I uninstalled the font and the Synctrayzor GUI went back to normal after a restart. It didn't affect the Syncthing web interface.
Is this behavior intentional ?

**Comment by canton7** [comment]
The font family which Syncthing uses is: "Helvetica Neue", Helvetica, Arial, sans-serif;

I suspect your system had a number of Helvetica fonts, none of which was called "Helvetica Neue" or "Helvetica", so the embedded browser just picked one, which happened to be "Helvetica Ultra Compressed". I suspect your other browser happened to pick another one.

If so, yes this would be intentional behaviour.
