### ISSUE TITLE
Synctrayzor is stuck at "Syncthing Starting..."

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#420]
**Please note that I searched the [_Issues_](https://github.com/canton7/SyncTrayzor/issues?utf8=%E2%9C%93&q=stuck%20on%20starting) list for this exact problem before reporting.**

Synctrayzor and Syncthing are getting stuck at the "Syncthing Starting..." splash screen upon opening the program on Windows 10 Pro x64, v1709.

I have tried running Synctrayzor through the Compatibility Troubleshooter running both Windows 8 and Windows Vista modes, with at least the program seeming to be more responsive and active (by outputting more logs) in the Windows Vista compat mode, _but I will leave that to be said_ by examining the logs themselves.

I have uploaded here a whole copy of my "logs" directory found under C:\Users\<username>\AppData\Roaming\SyncTrayzor\.

Attachments:
* [logs.zip](https://github.com/canton7/SyncTrayzor/files/1454519/logs.zip)
* [Screenshot 01](https://user-images.githubusercontent.com/9492083/32559025-2cc7ebe4-c474-11e7-9f0a-e28574568b9f.PNG)
  ![st-starting-stuck](https://user-images.githubusercontent.com/9492083/32559099-552979cc-c474-11e7-8ae7-ac18cda89e74.PNG)

**Comment by canton7** [comment]
Mind cranking the log level up to Debug then giving me an updated SyncTrayzor.log?

**Comment by antonio-gil** [comment]
Uh, well, I've the same issue, but it's a different scenario as in my case it happens in a Windows 7 x64 machine.

As far as I have seen it's _"somewhat"_ random, and the only probable cause (not quite sure how important is) that I've seen is that it seems to happen when I shutdown the machine and didn't close SyncTrayzor using the "Exit" command on the contextual menu of the systray icon, so I've the hypothesis that it could be related.

Curiously enough, that didn't happen on the other machine that I've on home, that is a Windows 10 x64 despite that I program an automatic shutdown for that one (I mention this because my hypothesis).

If there's no problem, and if I can use this thread for the issue, I'll upload the Debug log tonight, or (more) probably tomorrow (My TZ is UTC−6:00 / or CT/CST). Otherwise, I'll open a new issue and upload the log there.

Best regards!

**Comment by canton7** [comment]
Apologies for the late delay. Some debug logs would be very helpful, thanks!

**Comment by antonio-gil** [comment]
I'll upload them in a moment or two (kinda busy days, and I completely forgot about this)...

But, I think that I've found certain pattern (more accurate), at least in my case: it seems that this is present when the network connection isn't established yet.

**Comment by canton7** [comment]
Sorry for the delay - I don't think I get notified about edits, so didn't spot you'd added the log.

There are two things going on. The first is that my attempt to connection to Syncthing's API times out after 5 minutes, rather than 70 seconds, which is what it should be. Not sure that could be causing this, probably something deep in the windows networking stack. The second is that my attempt fails in an unexpected way, which I interpret incorrectly...

Would you mind testing this build? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.18.498/artifacts

**Comment by antonio-gil** [comment]
Hi. No problem with the delay.

Yeah, I'll check that build, and let you know what happens. Oh, and by the way, I'll be using the x64 version.

Best regards!

**Comment by antonio-gil** [comment]
Hi again.

I've been testing the build, and the reported issue seems to be gone, at least in my particular scenario.

Regards.

**Comment by canton7** [comment]
Cool! I'll get that released at some point.

**Comment by antonio-gil** [comment]
Cool, that's great!

Thank you for your support!
