### ISSUE TITLE
Issue installing/upgrading to 1.1.20.0

### ISSUE THREAD

**Issue by newstarshipsmell** [canton7/SyncTrayzor#439]
I was running a previous version (I believe it was 1.1.17.0) and kept receiving popup windows to update to 1.1.20.0 - when I tried clicking the update now button, the updater kept generating error messages that it couldn't modify some file (I did not note which file.) So I completely exited out of SyncTrayzor, went to Github and downloaded the newest installer for Win x64, and ran the installer. It generated the same error, so I ran it again with elevated Admin privileges, and it seemed to install/upgrade properly. When I launched it immediately from the post-install window, it worked normally and the Help menu item reported it was version 1.1.20.0.

Then when I closed out of it and relaunched SyncTrayzor via the start menu, it again triggered the upgrade popup menu, and the Help menu item reported it was version 1.1.17.0.

So I completely exited out of it again, uninstalled it, deleted the remaining folders in Program Files and AppData, logged into my Admin account and ran the installer from there, which ran normally.

Upon logging off my Admin account and reopening my User account, I clicked the (newly created) desktop shortcut to launch SyncTrayzor and was given the following error message:

![sterror0](https://user-images.githubusercontent.com/8490334/36948750-36dda916-1fa5-11e8-93da-b819d02b5991.png)

I couldn't copy/paste the text to/from the clipboard for some reason (despite being able to select-all and context menu-copy it) hence the screenshot instead. Clicking the log link displays this:

![sterror](https://user-images.githubusercontent.com/8490334/36948667-f688a16e-1fa3-11e8-94ea-43c1a56658ec.png)

Clicking close triggers a Windows prompt the program has stopped working and to check for solution/close program.

**Comment by newstarshipsmell** [comment]
The most recent installer I had prior to downloading the current version was 1.1.18.0, so that is probably what I was running at the time I attempted to upgrade to 1.1.20.0.

After receiving this error, I also experienced issues with the clipboard in general, for all programs (I could not copy/paste to/from it between any program windows) even after terminating/restarting explorer.exe. I had to reboot to fix the clipboard, so it seems to be somehow breaking that too.

**Comment by Hard-Wired** [comment]
Wow, that is bizarre. Just spit balling until canton chimes in, but It could be an installation glitch. On occasion I have had to completely uninstall/reinstall both Syncthing & SyncTrayzor to get things running smoothly again.

On a side note, it looks like you are running Windows 7... are you running any kind anti-virus, virtual machine or watchdog software that prevents applications form accessing user directories? There is a similar feature in Windows 10 / Defender that can cause this behavior if the application hasn't been given exclusive access permission.

**Comment by canton7** [comment]
> the updater kept generating error messages that it couldn't modify some file (I did not note which file.)

The installer should be automatically elevating itself to admin (and getting UAC to prompt you). So either Windows is failing to elevate it to an administrator user when asked, or the administrator user it elevates to doesn't have permission to access Program Files, etc. Could you check exactly which file it complains about, and also see which user it's elevated to (Task Manager will show you).

> Then when I closed out of it and relaunched SyncTrayzor via the start menu, it again triggered the upgrade popup menu, and the Help menu item reported it was version 1.1.17.0.

That suggests that maybe you previously had the 64-bit version installed, then installed the 32-bit version, or the other way around?

> Upon logging off my Admin account and reopening my User account, I clicked the (newly created) desktop shortcut to launch SyncTrayzor and was given the following error message:

It's failing to create its configuration directory `C:\Users\<You>\AppData\Roaming\SyncTrayzor`. Which is worrying, as a user should have access to its AppData directory...

> Clicking the log link displays this:

*That* is a bug - it's due to failing to create its configuration just before, but we shouldn't get this crash.

> After receiving this error, I also experienced issues with the clipboard in general, for all programs (I could not copy/paste to/from it between any program windows) even after terminating/restarting explorer.exe. I had to reboot to fix the clipboard, so it seems to be somehow breaking that too.

I've seen Adobe do that to my machine... I'm not doing anything special with the clipboard - I just present text using the standard windows UI controls, so I'm not sure why your clipboard's gotten confused I'm afraid.

There are a number of different issues here. The first I think is best explained by you switching between x86 and x64 versions. The second is something strange to do with permissions on your system: the user which Windows has decided is your administrator user doesn't appear to have access to Program Files (which I think is why the auto-install must have failed, unless you can add info on which file exactly was failing), and your own user doesn't seem to have access to its AppData folder. The final issue is clicking that link, which is mine to fix.

**Comment by newstarshipsmell** [comment]
Yeah, I'm running Comodo Internet Security Premium 10. Disabled Auto-Containment, and it works normally now. Thanks for the suggestion! Also, thanks for the awesome software.

**Comment by canton7** [comment]
Thanks for confirming.

Leaving this open to remind me to fix the link issue.
