### ISSUE TITLE
Syncthing crashes when I close the lid

### ISSUE THREAD

**Issue by jkaberg** [canton7/SyncTrayzor#5]
Ok, a bit unsure if SyncTrayzor should handle this so I'll let you decide

Whenever I close the lid on my laptop Syncthing seemingly crashes, and SyncTrayzor dosn't fire it up again when I open the lid

I'll report this over at Syncthing repo aswell

Edit: after some further investigations I noticed syncthing is still running in the background, SyncTrayzor just dosn't recognize it

**Comment by canton7** [comment]
Thanks, I'll look into this

**Comment by jkaberg** [comment]
Thanks, altho this might be a false positive - I dont know, just yet

Apparently now it seems to be working fine, IDK if has anything to do with me launching syncthing manually once (between orginal report and this post) and then re-launching SyncTrayzor after that

I'll keep you posted on my findings

**Comment by canton7** [comment]
I haven't been able to reproduce this. Yeah, if you start Syncthing outside of SyncTrayzor (and leave it running), then try and run SyncTrayzor, SyncTrayzor will try to start Syncthing and that Syncthing process will fall over, complaining that it can't access the database that's been locked by the first Syncthing process. That's why I added the menu option Syncthing -> Kill All Syncthing Processes.

SyncTrayzor normally can't communicate with any Syncthing process not started by SyncTrayzor, as they won't be using the right API key.

What are the exact symptoms you're seeing? What does "just doesn't recognise it" mean?

**Comment by jkaberg** [comment]
I can't reproduce this so I'll just close it

Sorry about the false posetive

**Comment by canton7** [comment]
That's fine - if you figure out what it was, let me know :)
