### ISSUE TITLE
Start Minimized for GUI not working

### ISSUE THREAD

**Issue by XceSx6** [canton7/SyncTrayzor#513]
Dear Dev,

Great app, but the SyncTrayzor "Start Minimized" in the bottom of the settings screen does not appear to have any effect..
Every boot, there is the GUI, regardless of this checkbox being marked.

Please address when you get the chance :)

**Comment by XceSx6** [comment]
And keep up the good work :D

**Comment by canton7** [comment]
Can you open the registry, browse to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`, find the key for `SyncTrayzor`, and tell me what the value of that is?

**Comment by XceSx6** [comment]
Value:

"D:\Programs\SyncTrayzorPortable-x64\SyncTrayzor.exe" -minimized

**Comment by asimoneo** [comment]
it also didn't work for me (autostartup), so had to create an entry in scheduler (works really more stable than registry)

**Comment by poisonborz** [comment]
+1 to this. Also a problem that this can (at least by ui logic) only be switched on tandem with autostart. This should be a standalone option and apply to all startups.

**Comment by canton7** [comment]
Would one of you please post your log file (File -> Settings -> Logging -> Show SyncTrayzor log file)? I want to see if it's being started and crashing, or whether Windows isn't starting it at all.

@poisonborz Are you referring to starting it minimized? Just pass the flag `-minimized` when you start it.

**Comment by poisonborz** [comment]
Ah thanks, that's it. As this is not so easy for average users, I'd still suggest to leave that checkbox always enabled, and rename that block to eg. "Startup options".

**Comment by canton7** [comment]
What do you mean, leave the checkbox always enabled? The checkbox is there so people can choose whether to start it minimized or not.

**Comment by poisonborz** [comment]
I think it wouldn't be a problem if the app starts _always_ minimized - I mean that could be a separate checkbox/flag (startup minimized, always minimized).
Some apps solve this by opening an alert if the app is run twice (because of confusion about this), informing the user that the app is already running and to look for it in the tray.

**Comment by canton7** [comment]
> I think it wouldn't be a problem if the app starts always minimized - I mean that could be a separate checkbox/flag (startup minimized, always minimized).

Again, I cannot tell the difference between these two cases. The app is just started. I cannot have separate options here, because *there is no way of telling whether the app was started from the start menu, or started automatically at startup*.

If the app is running in the tray and someone launches it from the start menu, then it does restore the instance that's running in the tray.

**Comment by canton7** [comment]
Still waiting for the info in [this comment](https://github.com/canton7/SyncTrayzor/issues/513#issuecomment-578124808)

**Comment by canton7** [comment]
Closing as noone is providing the log files I requested. Please re-open if you have these.
