### ISSUE TITLE
get some cheap DV cert to fix problems with default enabled "mswindows smart screen"

### ISSUE THREAD

**Issue by MrTAtHH** [canton7/SyncTrayzor#525]
hi,

![2019-08-10 09_04_11-Benutzerkontensteuerung](https://user-images.githubusercontent.com/53964219/62818896-12dfa280-bb4e-11e9-914a-f3d6be327d7f.png)

even if you cant read and understand german, you see my point, this window looks somewhat scary or even threatening in the ey of an non technical user who dose not know the meaning of that. So could you get a simple cheap certificat and sing your binarys with it? I guess even a free one (like lets encrypt) should work because windows dose not show any warning if the certificate is not valid anymore...

With kind regards

MrT

**Comment by canton7** [comment]
>  I guess even a free one (like lets encrypt) should work because windows dose not show any warning if the certificate is not valid anymore...

The installer is already signed with a self-signed cert, and you still got the warning in your screenshot, so I'm not entirely sure that's true.  Do you have a source?

The cheapest code signing certs I've found start at about £100/year -- that's a lot of money for an open-source project that doesn't generate any income!

I think most people are fairly used to seeing that notice - it only looks slightly different to the normal UAC popup - certainly less than 0.002% of them complain. It would certainly be nice to properly sign everything (and that would help with SmartScreen), but I'm not entirely convinced that it's worth the (not insignificant) cost.

**Comment by JLJTGR** [comment]
> I guess even a free one (like lets encrypt) should work because windows dose not show any warning if the certificate is not valid anymore...

I think it's important to understand that Let's Encrypt is not a code signing authority.  They can safely issue server certificates because they are able to verify the owner of a domain without doubt.  The certificate only verifies the server is valid and the connection was encrypted by the domain owner...  not that the server is owned by someone trustworthy nor that the data from the server is safe for use.

You can inspect a free certificate and see that it is not usable for code signing....  (Left is a free HTTPS certificate, right is a paid certificate for a signed installer)
![2019-10-13 16_13_25-Certificate](https://user-images.githubusercontent.com/5780236/66721949-186b9a00-edd6-11e9-8f7c-22dc3e3edb4b.png)

**Comment by uroni** [comment]
Please consider a code signing certificate like from https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-1022.html

As is, someone can take over your github account, release compromised software and we wouldn't know and install said software. It's not just about bypassing an annoying Windows screen...

**Comment by canton7** [comment]
Without wanting to go into too much detail, in order to take over my github account, someone would need:

1. Access to all files on my computer
2. Knowledge of a strong, unique password, which means either:
    1. A keylogger running on my computer, or
    2. Access to me, and they're hitting me with a bit of rubber piping
3. Access to my MFA device (again, access to me)

So to get that far, someone already has access to everything. Either they've got access to all of my files and my MFA device (which I haven't noticed) and they're watching everything I do, or they've got a means of coercing me into doing whatever they want.

An extra signing step isn't going to help in this case. They've already got access to everything they need to sign a release themselves.

Also remember that most people only download a release once: after that, automatic upgrades (which are signed) take over. So noone is going to notice that releases were previously signed, but then stop being signed.

Even if they did, people don't care. Everyone who's installed it so far has been fine with the fact that it's not signed, so I don't think a lack of signing is going to stop anyone in the future.

Finally, releases are signed on the Releases page, before you download.

**Comment by canton7** [comment]
If you're paranoid (that's not a bad thing, but you _would_ have to be paranoid to spot that the code signature changed between releases) you can check the existing signature yourself [as described on the security page](https://github.com/canton7/SyncTrayzor/blob/master/security/README.md).

Bur again, if someone has managed to compromise my github account, they probably also have my private key and passphrase.
