### ISSUE TITLE
why on earth does a sync program not. sync. the. bloody. folder.

### ISSUE THREAD

**Issue by artlessknave** [canton7/SyncTrayzor#527]
set it up, and its "out of sync" well no flipping duh, *you're supposed to sync it*, that's the whole point.
that is so INFURIATING. i don't CARE that they are out of sync. make them in sync to whatever was the last modified, the contents don't matter, being in sync is what matters.

**Comment by artlessknave** [comment]
and while I'm already venting, why the hell does it make 1000's of "conflict" files. if its not the newest version frikking delete it and put the newest version

**Comment by canton7** [comment]
This sounds like a Syncthing issue - it's not related to SyncTrayzor specifically.

I suggest posting [on the forum](https://forum.syncthing.net). You will be asked for enough details so that other people can actually understand the problem you're having and what might be causing it - screenshots from both devices is normally a good starting point. 

I do suggest taking a breather first though - as understandable as frustration is, it doesn't normally help with debugging a problem :)

**Comment by artlessknave** [comment]
oh, my bad, I didn't notice this was trayzor specific. one of the problems with being pissed off
