### ISSUE TITLE
More icon colours

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#53]
From Martin, via email.

So the key question is: how do I know if everything is working. So I 
would differentiate the following states:

  1. currently syncing: blue & spinning
  2. each folder has at least one node it is connected to (i.e. if
    required each folder is able to sync to at least one remote node) =>
    blue (normal)
  3. at least one folder has at least one node it is connected to (i.e.
    physical Internet connection seems to work, but it cannot be
    guaranteed, that all changes on the local node reach remote nodes)
    => some other color/icon (dark blue?), or an exclamation mark over
    the icon, or ...
  4. no single folder has at least one node it is connected to (i.e.
    there is no connection that is useful for syncing) => gray
    "disconnected" (logically, not necessarily physically)
  5. Of course it would be great to see the Out-Of-Sync state, but if
    there are problems, this could be postponed to a later release (or
    better: set as option if this should be displayed) => some other
    color/icon, or an exclamation mark over the icon, or ..

**Comment by chucic** [comment]
Don't know if this is meant for discussion, but I will through my opinion anyway :innocent::

1. This is current behaviour, right? And it's also spinning when scanning and exchanging indexes, I think.
2. (and also 3.) I think this is useless. Different look of an icon should tell you that:
 1. Something is wrong (currently grey when Syncthing is not running/connected)
 2. Something is happening (currently spinning, see 1.)
3. (still about 2.+3. - don't know how to format it) It shouldn't have another (semi-OK) state causing that some users (and maybe only on some devices) will never achieve full-OK state and when they do, it will cause more confusion than it would be its benefit. Syncing multiple folders to multiple devices simply isn't something what could be fitted to one icon without need to open GUI from time to time. Another reason against this: Syncthing itself also doesn't differentiate between those 2 states of folder. When no other device sharing that folder is connected, folder is "Up to date". (I know that Syncthing GTK does differentiate those, but it does it in the main window and it has its own GUI. Syncthing itself could have this "Offline" folder state too, but that is for another debate.) This also means that folders in GUI looks exactly the same for one folder having one node connected (one icon colour) or all folders having one node connected (other icon colour), causing confusion which most users won't be able to figure out (I think me included, so for me this is the strongest argument against).
4. Sounds good, but if this would be grey, then "Syncthing not running/disconnected" would have to be some other colour (and red/orange are "error"/"warning" colours and that is not a good idea because Syncthing could be down for a reason, i.e. "I don't want to sync now but leaving SyncTrayzor running"), so I would suggest dark blue as a transition between blue "OK" and grey " Syncthing down".
5. I either didn't understand this (because when we're "Out of state", we are "Syncing" and spinning blue apply here) or it is "Master folder only" case of use (rare, but legit, with "Propagate changes" in right click menu even more legit?) or it is the same as 2.+3., meaning: Keep it reasonable and simple, its Windows only (any plans to go multi-platform?) app after all with main purpose to bring Syncthing to those Dropbox/Google Drive masses (I think, because to bring BTSync people Syncthing itself seem good enough for me) and they will have enough troubles to set it right and understand purpose of multiple folders.

This took me more than an hour to create so I hope it's not worthless and I didn't forget anything important. Will come back if I did (and if this post will still be here :wink:).

P.S.: Apologies to Windows users (I'm one of them), if you're reading this then "masses" not applies to you.
P.P.S.: I'm overusing brackets, I know :stuck_out_tongue_winking_eye:

**Comment by canton7** [comment]
This issue is half a reminder to myself, and half an opportunity for discussion.

Thanks - I'll go over your comments in detail later, when I have some time. The main thing I'm worried about is remaining obvious: there's nothing worse than a cryptic icon, where you can never remember what state each of the colours mean.

**Comment by canton7** [comment]
Right!

1. Is almost correct - it actually spins when any data is being transferred, up or down (which should cover index transfers, uploading, downloading, etc).

I'm inclined to agree with you on pretty much all points. The only remaining suggestion, I think, is "no single folder has at least one node it is connected to", which I'm interpreting as "at least one folder will not sync, because it's not connected to anything". An icon which is half blue and half grey might be a good option here - but I'm not sure how useful it is. One of my folders is almost never connected to another device.

**Comment by canton7** [comment]
I think this has been overtaken by the new icons - paused, warning, etc.

Following these, I don't really want to change the icon unless it's the grab the user's attention (because there's something that they should know about, that isn't "normal operation").
