### ISSUE TITLE
White Screen at launch

### ISSUE THREAD

**Issue by borrougagnou** [canton7/SyncTrayzor#578]
Hello, I have a problem,
I can't launch SyncTrayzor, I have a white screen when I launch the program, I don't have configured something :
![IMG_20200922_083024](https://user-images.githubusercontent.com/10796546/93850262-01078300-fcae-11ea-9180-94ca59dfc38b.jpg)

**Comment by canton7** [comment]
I have no explanation for that I'm afraid: I've never seen anything like it. Since it's not drawing even the menu bar, I think this is between your computer and the .NET Framework: I don't think my code is involved. Since WPF uses DirectX, I suspect that might be broken on your machine, but I'm not sure what the steps are to debugging it.

Closing as I don't think there's anything I can do to help I'm afraid.
