### ISSUE TITLE
How to turn off all tray balloon messages?

### ISSUE THREAD

**Issue by snakyjake1** [canton7/SyncTrayzor#613]
I get a lot of tray balloon messages.
How do I turn off and disable the balloon messages that tell me when a sync is finished?

![image](https://user-images.githubusercontent.com/8312560/103571257-7a745b80-4ec2-11eb-9b52-3e6842ff588d.png)

v1.1.27

**Comment by josh-berry** [comment]
+1, would really like an answer to this. I installed SyncTrayzor maybe 15 minutes ago and the constant notifications of "hey this file was updated from another device" are already super annoying.

**Comment by canton7** [comment]
This is a per-folder setting, see the "Folders" tab, as the text "See the 'Folders' tab for per-folder notification settings" instructs you to. 

If you've got suggetions on making this clearer, I'm allears!

**Comment by josh-berry** [comment]
> This is a per-folder setting, see the "Folders" tab, as the text "See the 'Folders' tab for per-folder notification settings" instructs you to.

You know, I totally missed this text when I looked at the dialog. 🤦 Thanks for pointing it out!

> If you've got suggestions on making this clearer, I'm all ears!

Maybe put it at the top of the frame (above the checkboxes, right underneath the "Tray Icon" heading)? It's kind of sandwiched between the checkboxes and the "Animate tray icon" dropdown, so that might be why I missed it when scanning the options.

You might also consider making all the descriptive text _italic_ although that might be a bit much. Just a thought to try out and see if you like it.

Thanks again, and I hope the suggestions help. 😄

**Comment by canton7** [comment]
I've moved things around a bit. Hopefully that's clearer!
![image](https://user-images.githubusercontent.com/568104/113597077-197c3100-9633-11eb-9418-0b2b36ce4c01.png)

**Comment by josh-berry** [comment]
Thanks, I think that will help!

**Comment by bilogic** [comment]
Haha, thanks @canton7!

Apparently, even the additional dialog was not enough for me. 

For context, I tried configuring it about 10 hours ago, look through it several times, even clicked on the `Folders` tab, but it just did not connect for me. I finally decided to file an issue only to be pointed here almost immediately. I feel really blind now.

I took another look, why not:

1. Move `Show Tray Icon only on close` to the `SyncTrayzor` group (This is icon behavior)
2. Move `Animate Tray Icon:` to the `SyncTrayzor` group (This is icon behavior)
3. Move the rest of `Tray Icon` and `Alerts` to `Folders` (These are notification types)
4. Rename `Folders` as `Notifications` or `Toasts`

The issue I see is that notification types and tray icon behavior were mixed together. It should be crystal clear once they are separated. `Alerts` could also be expanded so that they can have a sticky alert and notifications. I kept focusing on the `Tray Icon` as I assumed all notifications should be configured there.

Just my 2 cents. :) Thank you!

**Comment by canton7** [comment]
The Folders tab exists because there are many sorts of per-folder settings. However, I really need to properly ditch the filesystem watcher at some point (it's *almost* pointless currently, as Syncthing's watcher will replace it in almost all cases, but I haven't wanted to pull the plug).

If those are removed, then the Folders tab will only contain per-folder notifications, and so I agree it makes sense to bundle all of the notifications together in a single tab.
