### ISSUE TITLE
Installer offers Synthing 0.11 but installs 0.10.30

### ISSUE THREAD

**Issue by chosenken** [canton7/SyncTrayzor#63]
I have downloaded the latest 64 bit installer from releases (build 1.0.15) and selected the beta 0.11 build of syncthing.  However once SynkTrazor starts up I see that it is actually running with syncthing 0.10.30.  I tried deleting the syncthing.exe before running the installer again and it installed the old version still.

**Comment by canton7** [comment]
Did you have SyncTrayzor previously installed (using Syncthing 0.10)? If so, delete `C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe`.

I'll just explain a little bit: `syncthing.exe` is installed by the installer into `C:\Program Files\SyncTrayzor\syncthing.exe`. However, in order to let it auto-upgrade, SyncTrayzor copies it to `C:\Users\<You>\AppData\Roaming\SyncTrayzor\syncthing.exe`, and executes it from there. It will be copied if:

1. It doesn't exist in `AppData`
2. The file in `Program Files` is never than the file in `AppData`.

I suspect, in your case, it already exists in `AppData`, but the version in `AppData` is somehow newer than the version in `Program Files`.

I've got an idea for how to make this more robust (and not rely on file Last Write times), which I'll get in soon.
