### ISSUE TITLE
The installer did not overwrite "AppData\Roaming\SyncTrayzor\syncthing.exe"

### ISSUE THREAD

**Issue by mowanotm** [canton7/SyncTrayzor#652]
Installer of version v1.1.28 (not Portable version)
Problem: The file "syncthing.exe" inside "C:\Program Files\SyncTrayzor\" is successfully updated, but the file inside "AppData\Roaming\SyncTrayzor\" remained in older version.
Solution: Manually overwrite the file in "AppData\Roaming\SyncTrayzor\"

**Comment by canton7** [comment]
That's the intended behaviour. Syncthing auto-updates, so the version in AppData should always be the most recent version. 

Forcefully overwriting the version in AppData actually risks *downgrading* Syncthing (the version of Syncthing in the installer is always older than the latest version). Downgrading Syncthing is a problem, because older versions won't work with databases created by newer versions.

There's also the consideration that it's just not really possible for a system-wide installer to update individual users' files in AppData. Sure it can fiddle with the files created by the user running the installer, but what about any other users on the system?

**Comment by mowanotm** [comment]
Unfortunately, I put the server in a semi-isolated setup. Syncthing have no direct internet access and I did noticed for three years... '#facepalm

**Comment by canton7** [comment]
If you manually delete the copy in AppData, SyncTrayzor will replace it with the version from Program Files next time it runs. 

I'm afraid I don't think there's anything actionable here: things are the way they are for very good reasons, and forcefully overwriting the user's copy of Syncthing in AppData will break many people's setups
