### ISSUE TITLE
syncthing profile

### ISSUE THREAD

**Issue by tjldtf** [canton7/SyncTrayzor#88]
I looked at SyncTrayzor (cf. https://forum.syncthing.net/t/url-to-open-sync-folder-from-gui/2718/6) and find it a great work. When starting it the first time, it created a new syncthing profile (I think in \data\syncthing). Since I already played a bit with syncthing berfore there's already a profile in the App folder of the user profile. My would thus suggest to use this default folder of syncthing.

**Comment by canton7** [comment]
If you downloaded the portable version, then yes, it tells Syncthing to use a profile in `data\syncthing`. If you go to File -> Settings -> Syncthing -> Advanced, and uncheck 'Use custom home for Syncthing', then it will use Syncthing's default profile location.

If you had downloaded the installer instead of the portable version (the installer is recommended: auto-upgrades are much smoother), then it would have used Syncthing's default profile location by default.

**Comment by canton7** [comment]
(This is all [in the README](https://github.com/canton7/SyncTrayzor#what-will-synctrayzor-do-to-my-system), albeit at the bottom...)

**Comment by tjldtf** [comment]
I see, thanks for the explanation.

**Comment by canton7** [comment]
The people who use the portable version are typically either:

1. Putting Syncthing onto a USB stick and using it across multiple computers
2. Want to put Syncthing and its index into an encrypted filesystem / container

Both of these groups want Syncthing to put its profile info `data\`, so the current defaults make the most sense. I may, however, move that 'Use custom home for Syncthing' out of the 'Advanced' section, to make it a bit more obvious.
