### ISSUE TITLE
README references 0.11 beta

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#97]
0.11 is out of beta now, I was going to submit a PR removing the whole paragraph for this section but  was unsure whether you still give the option to install 0.11 or 0.10 and whether or not you still call it "beta" on the installer

**Comment by canton7** [comment]
Ah bollocks, I had it on my TODO list to update that bit of the README, but it must have slipped me by. 

The installer no longer supports 0.10 - it's been like that for a while (although SyncTrayzor still supports it if you go around manually moving binaries around, or have just never upgrade Syncthing since first installing it).

**Comment by canton7** [comment]
Do you want to do this, or shall I?

**Comment by Rewt0r** [comment]
Beat me to it! Thanks
